//login
export const LOGIN_SUCCESS =`LOGIN_SUCCESS`
export const LOGIN_FALSED =`LOGIN_FALSED`
export const IS_LOADING_LOGIN=`IS_LOADING_LOGIN`
//register
export const REGISTER_SUCCESS =`REGISTER_SUCCESS`
export const REGISTER_FALSED =`REGISTER_FALSED`
export const IS_LOADING_REGISTER=`IS_LOADING_REGISTER`
//Users
export const GET_USER=`GET_USER`
export const IS_LOADING_GET_USER=`IS_LOADING_GET_USER`
export const ADD_NOTI=`ADD_NOTI`
export const GET_NOTI=`GET_NOTI`
//Courese
export const GET_COURSES=`GET_COURSES`
export const GET_COURSES_FALSED=`GET_COURSES_FALSED`
export const IS_LOADING_COURSES=`IS_LOADING_COURSES`
export const DELETE_COURESE=`DELETE_COURESE`
