//login
export const LOGIN_SUCCESS =`LOGIN_SUCCESS`
export const LOGIN_FALSED =`LOGIN_FALSED`
export const IS_LOADING_LOGIN=`IS_LOADING_LOGIN`
//register
export const REGISTER_SUCCESS =`REGISTER_SUCCESS`
export const REGISTER_FALSED =`REGISTER_FALSED`
export const IS_LOADING_REGISTER=`IS_LOADING_REGISTER`